# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- greenkeeper/*

variables:
  BuildConfiguration: 'Release'

jobs:

  - job: 'net_core'
    displayName: '.NET Core Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .net core 3.1'
        inputs:
          packageType: 'sdk'
          version: '3.1.100'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Restore'
        inputs:
          command: 'restore'
          projects: './src'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Build'
        inputs:
          command: 'build'
          arguments: '-c $(BuildConfiguration) --no-restore'
          projects: './src'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Run Tests'
        inputs:
          command: 'test'
          projects: './src'
          publishTestResults: false
          arguments: '--configuration $(BuildConfiguration) --logger "trx;LogFileName=TestResults.trx" --logger "xunit;LogFileName=TestResults.xml" --results-directory ./BuildReports/UnitTests  /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit.*]*'          

      - task: PublishTestResults@2
        displayName: 'Publish .NET Core test results'
        inputs:
          testRunTitle: NETCore
          testResultsFormat: 'XUnit'
          testResultsFiles: '**/TestResults.xml'          

  # Angular APP's
  - job: 'angular'
    displayName: 'Angular Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Npm@1
        displayName: 'NPM - Install - UserManagement'
        inputs:
          command: install
          workingDir: src/Frontend/Jp.UserManagement

      - task: Npm@1
        displayName: 'NPM - Test - UserManagement'
        inputs:
          command: custom
          customCommand: 'run test -- --watch=false --code-coverage'
          workingDir: src/Frontend/Jp.UserManagement

      # - task: Npm@1
      #   displayName: 'NPM - E2E - UserManagement'
      #   inputs:
      #     command: custom
      #     customCommand: 'run e2e'
      #     workingDir: src/Frontend/Jp.UserManagement            

      - task: Npm@1
        displayName: 'NPM - Build Prod - UserManagement'
        inputs:
          command: custom
          customCommand: 'run build'
          workingDir: src/Frontend/Jp.UserManagement

      - task: PublishTestResults@2
        displayName: 'Publish Angular test results'
        inputs:
          testRunTitle: Angular
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"    

      - task: PublishTestResults@2
        displayName: 'Publish Angular E2E test results'
        inputs:
          testRunTitle: Angular_E2E
          testResultsFormat: JUnit
          testResultsFiles: "**/junit*.xml" 
          

  - job: 'docker'
    displayName: 'Docker files'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Docker - Build - API'
        inputs:
          command: 'build'
          Dockerfile: 'api.dockerfile'

      - task: Docker@2
        displayName: 'Docker - Build - UserManagement'
        inputs:
          command: 'build'
          Dockerfile: 'users.dockerfile'

      - task: Docker@2
        displayName: 'Docker - Build - SSO'
        inputs:
          command: 'build'
          Dockerfile: 'sso.dockerfile'