version: '3.5'
services:
  envoygateway:
    build: Envoy/
    networks:
      - envoy_network
    ports:
      - "9901:9901"
      - "10000:10000"

  webapi1:
    build:
      context: .
      dockerfile: Web.Api1/Dockerfile
    networks:
      - envoy_network
    ports:
      - "7001:80"
    # environment: 
    #   ASPNETCORE_URLS: "https://+;http://+"
    #   ASPNETCORE_HTTPS_PORT: "7003"
    #   ASPNETCORE_ENVIRONMENT: "Development"

  webapi2:
    build:
      context: .
      dockerfile: Web.Api2/Dockerfile
    networks:
      - envoy_network
    ports:
      - "7002:80"
    # environment: 
    #   ASPNETCORE_URLS: "https://+;http://+"
    #   ASPNETCORE_HTTPS_PORT: "7004"
    #   ASPNETCORE_ENVIRONMENT: "Development"

networks:
  envoy_network: